<?php

/**
 * @file
 * Primary module hooks for Tufting-Customization Custom module.
 */

use Drupal\Core\Entity\Display\EntityFormDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;

function tufting_customization_theme($existing_theme, $type, $theme, $path) {
  return [
    'portal_header_template' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'portal-header',
      'base hook' => 'block',
    ],
    'portal_footer_template' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'portal-footer',
      'base hook' => 'block',
    ],
    'home_events_template' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'home-events',
      'base hook' => 'block',
    ],
    'branch_gallery_page' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'branch-gallery',
    ],
     'events_template' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'events',
      'base hook' => 'block',
    ],
    'event_gallery_page' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'event-gallery',
    ],
  ];
}







/**
 * Implements template_preprocess_block().
 */
function tufting_customization_preprocess_block(&$variables) {
  if (isset($variables['elements']['#base_plugin_id']) && $variables['elements']['#base_plugin_id'] === 'block_content') {
    $entity = $variables['elements']['content']['#block_content'];

    if ($entity->bundle() === 'about_company') {
    if ($entity->get('field_machine_name')->value == 'about_company_section') {
        if (!$entity->get('field_image')->isEmpty()) {
          $media_entity = $entity->get('field_image')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['section_1_image'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }
         if (!$entity->get('field_image_2')->isEmpty()) {
          $media_entity = $entity->get('field_image_2')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['section_2_image'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }
         if (!$entity->get('field_image_3')->isEmpty()) {
          $media_entity = $entity->get('field_image_3')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['section_3_image'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }
      }
    }


    if ($entity->bundle() === 'hero_banner') {
      if ($entity->get('field_machine_name')->value == 'intro_banner') {

        if (!$entity->get('field_image')->isEmpty()) {
          $media_entity = $entity->get('field_image')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['bg_image'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }

        if ($entity->hasField('field_video') && !$entity->get('field_video')->isEmpty()) {
          $fid = $entity->get('field_video')->target_id;
          $file = \Drupal::service('entity_type.manager')->getStorage('file')->load($fid);

          if ($file) {
            $video_url = \Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
            $variables['video_url'] = $video_url;
            $play_str = '';
            if ($entity->hasField('field_autoplay_video') && !$entity->get('field_autoplay_video')->isEmpty() && $entity->get('field_autoplay_video')->value == 1) {
              $play_str .= 'autoplay ';
            }
            if ($entity->hasField('field_loop_video') && !$entity->get('field_loop_video')->isEmpty() && $entity->get('field_loop_video')->value == 1) {
              $play_str .= 'loop ';
            }
            if ($entity->hasField('field_mute_video') && !$entity->get('field_mute_video')->isEmpty() && $entity->get('field_mute_video')->value == 1) {
              $play_str .= 'muted ';
            }

            $variables['mime_type'] = $file->getMimeType();
            $variables['play_str'] = $play_str;
        }
        } else {
          $variables['video_url'] = [];
        }

      }


      if ($entity->get('field_machine_name')->value == 'visit_our_showroom') {

        if (!$entity->get('field_image')->isEmpty()) {
          $media_entity = $entity->get('field_image')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['bg_image'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }

        if ($entity->hasField('field_video') && !$entity->get('field_video')->isEmpty()) {
          $fid = $entity->get('field_video')->target_id;
          $file = \Drupal::service('entity_type.manager')->getStorage('file')->load($fid);

          if ($file) {
            $video_url = \Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
            $variables['video_url'] = $video_url;
            $play_str = '';
            if ($entity->hasField('field_autoplay_video') && !$entity->get('field_autoplay_video')->isEmpty() && $entity->get('field_autoplay_video')->value == 1) {
              $play_str .= 'autoplay ';
            }
            if ($entity->hasField('field_loop_video') && !$entity->get('field_loop_video')->isEmpty() && $entity->get('field_loop_video')->value == 1) {
              $play_str .= 'loop ';
            }
            if ($entity->hasField('field_mute_video') && !$entity->get('field_mute_video')->isEmpty() && $entity->get('field_mute_video')->value == 1) {
              $play_str .= 'muted ';
            }

            $variables['mime_type'] = $file->getMimeType();
            $variables['play_str'] = $play_str;
        }
        } else {
          $variables['video_url'] = [];
        }

      }



      if ($entity->get('field_machine_name')->value == 'hero_banner_top') {
        if (!$entity->get('field_image')->isEmpty()) {
          $media_entity = $entity->get('field_image')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['logo_image'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }

        if (!$entity->get('field_consultant_form_link')->isEmpty()) {
          $variables['booking_url'] = $entity->get('field_consultant_form_link')->value;
        }

        $adv_query = \Drupal::entityTypeManager()->getStorage('block_content')->getQuery();
        $adv_query->condition('type', 'hero_banner'); // The block type machine name.
        $adv_query->condition('field_machine_name', 'advertise_pop_up'); // The field and value to look for.
        $adv_query->range(0, 1); // We only want one result.
        $adv_query->accessCheck(FALSE);
        $adv_block_ids = $adv_query->execute();

        if (!empty($adv_block_ids)) {
          $block_id = array_shift($adv_block_ids);
          $block_content = \Drupal::entityTypeManager()->getStorage('block_content')->load($block_id);
          $variables['adv_title'] = $block_content->get('field_title')->value;
          $variables['adv_sub_title'] = $block_content->get('field_sub_title')->value;
          $variables['adv_link_text'] = $block_content->get('field_consultant_form')->value;
          $variables['adv_link_url'] = $block_content->get('field_consultant_form_link')->value;

          if ($block_content->hasField('field_image') && !$block_content->get('field_image')->isEmpty()) {
              if (!$block_content->get('field_image')->isEmpty()) {
                $media_entity = $block_content->get('field_image')->entity;

                if ($media_entity) {
                  $image_source_field = $media_entity->get('field_media_image');

                  if (!$image_source_field->isEmpty()) {
                    $file_uri = $image_source_field->entity->getFileUri();
                    $variables['adv_logo_image_url'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
                  }
                }
              }
          }


        }

      }

    }

    if ($entity->bundle() === 'design_dreams') {
      if ($entity->get('field_machine_name')->value == 'design_dreams') {
        if (!$entity->get('field_image')->isEmpty()) {
          $media_entity = $entity->get('field_image')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['design_dreams_image_1'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }

        if (!$entity->get('field_image_2')->isEmpty()) {
          $media_entity = $entity->get('field_image_2')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['design_dreams_image_2'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }

        if (!$entity->get('field_image_3')->isEmpty()) {
          $media_entity = $entity->get('field_image_3')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['design_dreams_image_3'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }

         if ($entity->hasField('field_video') && !$entity->get('field_video')->isEmpty()) {
          $fid = $entity->get('field_video')->target_id;
          $file = \Drupal::service('entity_type.manager')->getStorage('file')->load($fid);

          if ($file) {
            $video_url = \Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
            $variables['video_url'] = $video_url;
            $play_str = '';
            if ($entity->hasField('field_autoplay_video') && !$entity->get('field_autoplay_video')->isEmpty() && $entity->get('field_autoplay_video')->value == 1) {
              $play_str .= 'autoplay ';
            }
            if ($entity->hasField('field_loop_video') && !$entity->get('field_loop_video')->isEmpty() && $entity->get('field_loop_video')->value == 1) {
              $play_str .= 'loop ';
            }
            if ($entity->hasField('field_mute_video') && !$entity->get('field_mute_video')->isEmpty() && $entity->get('field_mute_video')->value == 1) {
              $play_str .= 'muted ';
            }

            $variables['mime_type'] = $file->getMimeType();
            $variables['play_str'] = $play_str;
          }
          } else {
            $variables['video_url'] = [];
          }

      }
    }



     if ($entity->bundle() === 'bring_your_design') {
      if ($entity->get('field_machine_name')->value == 'bring_your_design') {
        if (!$entity->get('field_image')->isEmpty()) {
          $media_entity = $entity->get('field_image')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['bring_your_design_bg_image'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }

        if (!$entity->get('field_image_2')->isEmpty()) {
          $media_entity = $entity->get('field_image_2')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['bring_your_design_image_1'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }

        if (!$entity->get('field_image_3')->isEmpty()) {
          $media_entity = $entity->get('field_image_3')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['bring_your_design_image_2'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }

        if (!$entity->get('field_bring_image_3')->isEmpty()) {
          $media_entity = $entity->get('field_bring_image_3')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['bring_your_design_image_3'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }

        if (!$entity->get('field_image_4')->isEmpty()) {
          $media_entity = $entity->get('field_image_4')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['bring_your_design_image_4'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }

        if (!$entity->get('field_image_5')->isEmpty()) {
          $media_entity = $entity->get('field_image_5')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['bring_your_design_image_5'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }

        if (!$entity->get('field_image_6')->isEmpty()) {
          $media_entity = $entity->get('field_image_6')->entity;

          if ($media_entity) {
            $image_source_field = $media_entity->get('field_media_image');

            if (!$image_source_field->isEmpty()) {
              $file_uri = $image_source_field->entity->getFileUri();
              $variables['bring_your_design_image_6'] = \Drupal::service('file_url_generator')->generateAbsoluteString($file_uri);
            }
          }
        }

         if ($entity->hasField('field_video') && !$entity->get('field_video')->isEmpty()) {
          $fid = $entity->get('field_video')->target_id;
          $file = \Drupal::service('entity_type.manager')->getStorage('file')->load($fid);

          if ($file) {
            $video_url = \Drupal::service('file_url_generator')->generateAbsoluteString($file->getFileUri());
            $variables['video_url'] = $video_url;
            $play_str = '';
            if ($entity->hasField('field_autoplay_video') && !$entity->get('field_autoplay_video')->isEmpty() && $entity->get('field_autoplay_video')->value == 1) {
              $play_str .= 'autoplay ';
            }
            if ($entity->hasField('field_loop_video') && !$entity->get('field_loop_video')->isEmpty() && $entity->get('field_loop_video')->value == 1) {
              $play_str .= 'loop ';
            }
            if ($entity->hasField('field_mute_video') && !$entity->get('field_mute_video')->isEmpty() && $entity->get('field_mute_video')->value == 1) {
              $play_str .= 'muted ';
            }

            $variables['mime_type'] = $file->getMimeType();
            $variables['play_str'] = $play_str;
          }
          } else {
            $variables['video_url'] = [];
          }

      }
    }

  }
}
